# Generated by Django 2.1.3 on 2018-11-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181121_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_crud_authors', 'Create, Update, Delete Author records'),)},
        ),
    ]
